[package]
name = "timestamp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "timestamp"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
