[package]
name = "shuffle-optimized"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shuffle-optimized"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
regex = "1.10"
log = { workspace = true }
env_logger = { workspace = true }
